# Generated by Django 4.2.1 on 2023-06-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="descript",
            field=models.CharField(default="Товар хороший", max_length=100),
        ),
    ]
